# This is a re-usable workflow that is used by .github/workflows/check.yml to handle necessary setup
# before running Nix commands. E.g. this will install Nix and set up Magic Nix Cache
name: "Nix Setup"

on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
      platform:
        default: "ubuntu"
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  nix:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - name: "Set default git branch (to reduce log spam)"
        run: git config --global init.defaultBranch main

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: "Set up QEMU support"
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: "Install nix"
        uses: cachix/install-nix-action@master
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes fetch-tree
            allow-import-from-derivation = false
            extra-platforms = aarch64-linux

      - name: "Cachix Setup"
        uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          name: hyprland-community

      - name: "Nix Magic Cache"
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Run Input: ${{ inputs.command }}"
        run: "${{ inputs.command }}"
