name: Check Flake Validity

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "pyprland/**"
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "pyprland/**"
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  check:
    uses: ./.github/workflows/nix-setup.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: nix flake check --accept-flake-config --print-build-logs

  build:
    needs: [check]
    uses: ./.github/workflows/nix-setup.yml
    strategy:
      matrix:
        package:
          - pyprland
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: nix build .#${{ matrix.package }} --print-build-logs
